### ISSUE TITLE
AssertionError - Missing antelopev2

### ISSUE THREAD

**Issue by barakyo** [Francis-Rings/StableAnimator#20]
### Stacktrace

```
/home/user/mambaforge/envs/stableanimator/lib/python3.11/site-packages/torch/cuda/__init__.py:716: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
/home/user/mambaforge/envs/stableanimator/lib/python3.11/site-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/user/mambaforge/envs/stableanimator/lib/python3.11/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/home/user/mambaforge/envs/stableanimator/lib/python3.11/site-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/home/user/StableAnimator/app.py", line 263, in <module>
    face_model = FaceModel()
                 ^^^^^^^^^^^
  File "/home/user/StableAnimator/animation/modules/face_model.py", line 11, in __init__
    self.app = FaceAnalysis(
               ^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/stableanimator/lib/python3.11/site-packages/insightface/app/face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Despite attempting to download antelopev2 of insight face, when you run the app you'll still get an `AssertionError`. This is because after downloading antelopev2 gets extracted into another folder:

```
(stableanimator) ~/StableAnimator/models/antelopev2/antelopev2$ ls -l
total 417536
-rw-rw-r-- 1 user user 143607619 Dec 11 14:06 1k3d68.onnx
-rw-rw-r-- 1 user user   5030888 Dec 11 14:06 2d106det.onnx
-rw-rw-r-- 1 user user   1322532 Dec 11 14:06 genderage.onnx
-rw-rw-r-- 1 user user 260665334 Dec 11 14:06 glintr100.onnx
-rw-rw-r-- 1 user user  16923827 Dec 11 14:06 scrfd_10g_bnkps.onnx
```

It should be `~/StableAnimator/models/antelopev2/`

The manual workaround is simply to: `mv antelopev2/* .`

I haven't looked at the code yet for how antelopev2 is downloaded, but wanted to give you a heads up.

**Comment by Francis-Rings** [comment]
Hi, thank you for your suggestion! I find that there is a bug in the automatic download process of Antelopev2 and have updated the README file with the solution.
