### ISSUE TITLE
Training failed with error _pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by Yaqing2023** [Francis-Rings/StableAnimator#29]
I tried to run the training scripts but it failed with error
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/yaqing/miniconda3/envs/stableanimator/bin/python', 'train.py', '--pretrained_model_name_or_path=stabilityai/stable-video-diffusion-img2vid-xt', '--output_dir=/home/yaqing/ai/StableAnimator/checkpoints/Animation', '--data_root_path=/home/yaqing/ai/StableAnimator/animation_data', '--rec_data_path=/home/yaqing/ai/StableAnimator/animation_data/video_rec_path.txt', '--vec_data_path=/home/yaqing/ai/StableAnimator/animation_data/video_vec_path.txt', '--validation_image_folder=/home/yaqing/ai/StableAnimator/validation/ground_truth', '--validation_control_folder=/home/yaqing/ai/StableAnimator/validation/poses', '--validation_image=/home/yaqing/ai/StableAnimator/validation/reference.png', '--num_workers=8', '--lr_warmup_steps=500', '--sample_n_frames=16', '--learning_rate=1e-5', '--per_gpu_batch_size=1', '--num_train_epochs=6000', '--mixed_precision=fp16', '--gradient_accumulation_steps=1', '--checkpointing_steps=2000', '--validation_steps=500', '--gradient_checkpointing', '--checkpoints_total_limit=5000', '--resume_from_checkpoint=latest']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yaqing/miniconda3/envs/stableanimator/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/yaqing/miniconda3/envs/stableanimator/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Any idea what may be wrong?

**Comment by Francis-Rings** [comment]
Hi, I’ve never encountered this issue before. Based on the error message, it might be related to `spawn`. You could try modifying the multiprocessing method at Line 822 in `train.py`.

**Comment by Yaqing2023** [comment]
yes I tried to change spawn to fork, the error is gone; also in the shell script  it has CUDA_VISIBLE_DEVICES=3,2,1,0, i suppose you have 4 GPU for training. this needs to be updated for actual GPU numbers user has?
but i still can not run the training on my single GPU machine with 16G memory, even though i have only 2 sub-dir to train 00001 and 00002. It still runs OOM

**Comment by Francis-Rings** [comment]
> yes I tried to change spawn to fork, the error is gone; also in the shell script it has CUDA_VISIBLE_DEVICES=3,2,1,0, i suppose you have 4 GPU for training. this needs to be updated for actual GPU numbers user has? but i still can not run the training on my single GPU machine with 16G memory, even though i have only 2 sub-dir to train 00001 and 00002. It still runs OOM

I use 4 NVIDIA A100 80GB GPUs to train StableAnimator. The CUDA_VISIBLE_DEVICES variable specifies which GPUs are available for use. For example, if your machine has a single GPU, you should set CUDA_VISIBLE_DEVICES=0. Furthermore, I recommend using GPUs with at least 40GB of VRAM for training StableAnimator.
