### ISSUE TITLE
error after entering Python app.py

### ISSUE THREAD

**Issue by J-Ai-57** [Francis-Rings/StableAnimator#56]
(venv) D:\ai\StableAnimator>python app.py
D:\ai\StableAnimator\venv\Lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
D:\ai\StableAnimator\venv\Lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
D:\ai\StableAnimator\venv\Lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
D:\ai\StableAnimator\venv\Lib\site-packages\albumentations\__init__.py:24: UserWarning: A new version of Albumentations is available: 1.4.24 (you have 1.4.23). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
Traceback (most recent call last):
  File "D:\ai\StableAnimator\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeffr\miniconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\StableAnimator\venv\Lib\site-packages\diffusers\loaders\ip_adapter.py", line 36, in <module>
    from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection, SiglipImageProcessor, SiglipVisionModel
ImportError: cannot import name 'SiglipImageProcessor' from 'transformers' (D:\ai\StableAnimator\venv\Lib\site-packages\transformers\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ai\StableAnimator\app.py", line 16, in <module>
    from animation.pipelines.inference_pipeline_animation import InferenceAnimationPipeline
  File "D:\ai\StableAnimator\animation\pipelines\inference_pipeline_animation.py", line 11, in <module>
    from diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion import retrieve_timesteps
  File "D:\ai\StableAnimator\venv\Lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 24, in <module>
    from ...loaders import FromSingleFileMixin, IPAdapterMixin, StableDiffusionLoraLoaderMixin, TextualInversionLoaderMixin
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "D:\ai\StableAnimator\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ai\StableAnimator\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see its traceback):
cannot import name 'SiglipImageProcessor' from 'transformers' (D:\ai\StableAnimator\venv\Lib\site-packages\transformers\__init__.py)

(venv) D:\ai\StableAnimator>

**Comment by Francis-Rings** [comment]
Hi, please refer to #35. The issue seems to be that you haven't installed the correct version of the Transformers dependency.

**Comment by xinli2008** [comment]
try:
