### ISSUE TITLE
训练中验证阶段崩溃的问题

### ISSUE THREAD

**Issue by Jeremy-J-J** [Francis-Rings/StableAnimator#61]
大佬，请问一下，在训练中validation_steps验证阶段出现如下报错，可能是什么原因呢？
报错日志如下：
```
12/28/2024 18:24:04 - INFO - __main__ - Running validation... 
  0%|                                                                                                                                     | 0/25 [00:11<?, ?it/s]
[rank0]: Traceback (most recent call last):                                                                                               | 0/25 [00:00<?, ?it/s]
[rank0]:   File "/home/StableAnimator/train.py", line 1695, in <module>
[rank0]:     main()
[rank0]:   File "/home/StableAnimator/train.py", line 1531, in main
[rank0]:     log_validation(
[rank0]:   File "/home/StableAnimator/train.py", line 1658, in log_validation
[rank0]:     video_frames = pipeline(
[rank0]:   File "/root/miniconda3/envs/stableAnimator_py310/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/StableAnimator/animation/pipelines/validation_pipeline_animation.py", line 671, in __call__
[rank0]:     _noise_pred = self.unet(
[rank0]:   File "/root/miniconda3/envs/stableAnimator_py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/stableAnimator_py310/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/stableAnimator_py310/lib/python3.10/site-packages/accelerate/utils/operations.py", line 680, in forward
[rank0]:     return model_forward(*args, **kwargs)
[rank0]:   File "/root/miniconda3/envs/stableAnimator_py310/lib/python3.10/site-packages/accelerate/utils/operations.py", line 668, in __call__
[rank0]:     return convert_to_fp32(self.model_forward(*args, **kwargs))
[rank0]:   File "/root/miniconda3/envs/stableAnimator_py310/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/StableAnimator/animation/modules/unet.py", line 446, in forward
[rank0]:     sample = sample + pose_latents
[rank0]: RuntimeError: The size of tensor a (64) must match the size of tensor b (88) at non-singleton dimension 3
Steps:  25%|█████████████████████▎                                                               | 50/200 [1:07:19<3:21:58, 80.79s/it, lr=1e-5, step_loss=0.0991]
[rank0]:[W1228 18:24:28.733727992 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
```

**Comment by Francis-Rings** [comment]
Hi, this issue is likely caused by a dimension mismatch between the latents and pose latents. Please check the dimensions of your reference image and the corresponding human skeleton images to ensure they match.

**Comment by Jeremy-J-J** [comment]
> Hi, this issue is likely caused by a dimension mismatch between the latents and pose latents. Please check the dimensions of your reference image and the corresponding human skeleton images to ensure they match.

Thank you, I suspect it might be because my validation set is not of size 512x512 or 576x1024. I will conduct an experiment.
