### ISSUE TITLE
unexpected keyword argument 'use_cuda_graph'

### ISSUE THREAD

**Issue by kenmcguire** [Francis-Rings/StableAnimator#62]
(env1) (stableanimator) E:\AI\StableAnimator>python app.py
Traceback (most recent call last):
  File "E:\AI\StableAnimator\app.py", line 5, in <module>
    from diffusers.models.attention_processor import XFormersAttnProcessor
  File "E:\AI\StableAnimator\env1\Lib\site-packages\diffusers\models\attention_processor.py", line 35, in <module>
    import xformers.ops
  File "E:\AI\StableAnimator\env1\Lib\site-packages\xformers\ops\__init__.py", line 8, in <module>
    from .fmha import (
  File "E:\AI\StableAnimator\env1\Lib\site-packages\xformers\ops\fmha\__init__.py", line 10, in <module>
    from . import (
  File "E:\AI\StableAnimator\env1\Lib\site-packages\xformers\ops\fmha\triton_splitk.py", line 110, in <module>
    from ._triton.splitk_kernels import _fwd_kernel_splitK, _splitK_reduce
  File "E:\AI\StableAnimator\env1\Lib\site-packages\xformers\ops\fmha\_triton\splitk_kernels.py", line 632, in <module>
    _fwd_kernel_splitK_autotune[num_groups] = autotune_kernel(
                                              ^^^^^^^^^^^^^^^^
  File "E:\AI\StableAnimator\env1\Lib\site-packages\xformers\ops\fmha\_triton\splitk_kernels.py", line 614, in autotune_kernel
    kernel = triton.autotune(
             ^^^^^^^^^^^^^^^^
TypeError: autotune() got an unexpected keyword argument 'use_cuda_graph'

**Comment by Francis-Rings** [comment]
Hi, this issue is likely due to an incorrect installation of XFormer. Please refer to #35 for a detailed Windows installation tutorial.
